CREATE TABLE users
(
    id        INT AUTO_INCREMENT PRIMARY KEY,
    userName  VARCHAR(20) NOT NULL,
    email     VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fixedAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE plans
(
    id        INT AUTO_INCREMENT PRIMARY KEY,
    user_id   INT,
    postedBy  VARCHAR(20)  NOT NULL,
    title     VARCHAR(20)  NOT NULL,
    content   VARCHAR(200) NOT NULL,
    postedAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE comments
(
    id               INT AUTO_INCREMENT PRIMARY KEY,
    plan_id          INT,
    user_id          INT,
    comment          VARCHAR(100) NOT NULL,
    commentedBy      VARCHAR(20)  NOT NULL,
    commentedAt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    commentUpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id)
);